[project]
name = "silent-key"
version = "0.1.0"
description = "A New Age Identity Management Application for Everyone"
authors = [
    {name = "ShashwatAcharya",email = "shashwatacharya1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14.0,<4.0.0"
dependencies = [
    "django (>=6.0.1,<7.0.0)",
    "sqlalchemy (>=2.0.46,<3.0.0)",
    "psycopg[binary] (>=3.3.2,<4.0.0)",
    "environs (>=14.5.0,<15.0.0)",
    "segno (>=1.6.6,<2.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "click (>=8.4.2,<9.0.0)"
]

[dependency-groups]
dev = [
    "django (>=6.0.1,<7.0.0)",
    "pytest (>=9.0.2,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
