# Generated by Django 6.0.2 on 2026-02-17 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
            ],
            options={
                'verbose_name': 'Permission Role',
                'verbose_name_plural': 'Permission Roles',
                'db_table': 'permission_roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('is_mfa_enabled', models.BooleanField(default=False, help_text='Multi-factor authentication enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LOGIN', 'Login Event'), ('LOGOUT', 'Logout Event'), ('MFA', 'MFA Event'), ('VERIFICATION', 'Verification Event'), ('IDENTITY_CHANGE', 'Identity Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('BIOMETRIC', 'Biometric Event'), ('SESSION', 'Session Event'), ('SECURITY', 'Security Event'), ('ERROR', 'Error Event')], db_index=True, max_length=20)),
                ('action', models.CharField(help_text='Specific action performed', max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Sanitized request details')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Sanitized response details')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User involved in the event (null for system events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_type', models.CharField(choices=[('TOTP', 'Time-based OTP (Authenticator App)'), ('SMS', 'SMS OTP'), ('EMAIL', 'Email OTP'), ('BACKUP_CODE', 'Backup Recovery Codes'), ('SECURITY_KEY', 'FIDO2 Security Key'), ('BIOMETRIC', 'Biometric Authentication')], db_index=True, max_length=20)),
                ('secret_key', models.CharField(help_text='Encrypted OTP secret or credential', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Verification status of this factor')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('backup_data', models.JSONField(blank=True, default=dict, help_text='Backup codes or recovery data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Factor',
                'verbose_name_plural': 'Authentication Factors',
                'db_table': 'authentication_factors',
            },
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biometric_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACIAL', 'Facial Recognition'), ('IRIS', 'Iris Scan'), ('VOICE', 'Voice Recognition'), ('PALM', 'Palm Vein')], db_index=True, max_length=20)),
                ('template_data', models.BinaryField(help_text='Encrypted biometric template blob')),
                ('template_hash', models.CharField(help_text='SHA-256 hash for duplicate detection', max_length=256, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary biometric for authentication')),
                ('quality_score', models.FloatField(default=0.0, help_text='Biometric template quality score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Template',
                'verbose_name_plural': 'Biometric Templates',
                'db_table': 'biometric_templates',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('INTERNAL', 'Internal Identity'), ('FEDERATED', 'Federated Identity'), ('OAUTH', 'OAuth Provider'), ('SAML', 'SAML Provider')], default='INTERNAL', max_length=20)),
                ('unique_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Identity verification status')),
                ('verification_level', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Email Verified'), (2, 'Phone Verified'), (3, 'Full Verification')], default=0, help_text='Trust level of identity verification')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional identity attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'db_table': 'identities',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('EMAIL', 'Email Verification'), ('PHONE', 'Phone Verification'), ('DOCUMENT', 'Document Verification'), ('BIOMETRIC', 'Biometric Verification')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('verification_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('challenge_data', models.JSONField(default=dict, help_text='Challenge details (email, phone, etc.)')),
                ('proof_data', models.JSONField(blank=True, default=dict, help_text="User's proof submission")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=3)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'db_table': 'identity_verifications',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, help_text='Device identifier hash', max_length=256)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('INVALID', 'Invalid')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_mfa_verified', models.BooleanField(default=False, help_text='Whether MFA was completed for this session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for temporary roles', null=True)),
                ('assigned_by', models.ForeignKey(help_text='Admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='identity.permissionrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['category', 'status'], name='audit_logs_categor_71a777_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationfactor',
            index=models.Index(fields=['user', 'factor_type'], name='authenticat_user_id_eb93ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authenticationfactor',
            unique_together={('user', 'factor_type', 'secret_key')},
        ),
        migrations.AddIndex(
            model_name='biometrictemplate',
            index=models.Index(fields=['user', 'biometric_type'], name='biometric_t_user_id_ce8993_idx'),
        ),
        migrations.AddIndex(
            model_name='biometrictemplate',
            index=models.Index(fields=['template_hash'], name='biometric_t_templat_e09fc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometrictemplate',
            unique_together={('user', 'template_hash')},
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['user'], name='identities_user_id_bee57f_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['unique_identifier'], name='identities_unique__8ce97d_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['user', 'status'], name='identity_ve_user_id_4af846_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['verification_code'], name='identity_ve_verific_1a93e0_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['expires_at'], name='identity_ve_expires_6b02bd_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'status'], name='sessions_user_id_40f7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_token'], name='sessions_session_7633cd_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='sessions_expires_bbb852_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='user_roles_user_id_801a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
